# Tensorflow Regression

In [1]:

fileloc  = '/mnt/batch/tasks/shared/LS_root/mounts/clusters/compute-one/code/Users/karan.bhatti'

import sys
print(sys.path)
print()
#sys.path.append(f'{fileloc}')
print()
#print(sys.path)


['/mnt/batch/tasks/shared/LS_root/mounts/clusters/compute-one/code/Users/karan.bhatti', '/anaconda/envs/azureml_py38_PT_TF/lib/python38.zip', '/anaconda/envs/azureml_py38_PT_TF/lib/python3.8', '/anaconda/envs/azureml_py38_PT_TF/lib/python3.8/lib-dynload', '', '/anaconda/envs/azureml_py38_PT_TF/lib/python3.8/site-packages', '/anaconda/envs/azureml_py38_PT_TF/lib/python3.8/site-packages/azureml/_project/vendor']




In [2]:

class Data(object):
    pass

df = Data
summ = Data


In [3]:
import helpdesk as hd

In [4]:

import pandas as pd, numpy as np
from datetime import datetime

import random


In [5]:

DEBUG = True
seed = 1919


In [6]:

pd.set_option('display.max_rows', 50);
pd.set_option('display.max_columns', 50);
pd.set_option('display.width', 200);


In [7]:

modeling_dataset_name = 'modeling_dataset_2022-10-18.csv'

df_modeling = pd.read_csv(f'{fileloc}/{modeling_dataset_name}')

print(df_modeling.shape)
print()
print(df_modeling.columns.values.tolist())


(243382, 14)

['@id_DOG', 'DogName', 'y_runtime', 'TrainerName', '@id_RACE', 'RaceNum', 'RaceName', 'Track', 'x_dist', 'x_races_tot', 'position', 'ft_sp', 'x_no_prev_races', 'x_avg_speed_prev']


In [8]:

df_modeling.isna().sum()


@id_DOG                0
DogName                0
y_runtime              0
TrainerName            0
@id_RACE               0
RaceNum                0
RaceName               0
Track                  0
x_dist                 0
x_races_tot            0
position               0
ft_sp               1200
x_no_prev_races        0
x_avg_speed_prev       0
dtype: int64

In [9]:

features = ['x_dist','x_avg_speed_prev', 'x_no_prev_races', 'x_races_tot']
label = 'y_runtime'

'''
from sklearn.model_selection import train_test_split

# Split data 70%-30% into training set and test set
x_train, x_test, y_train, y_test = train_test_split(df_modeling[features].values, df_modeling[label].values, test_size=0.30, random_state = seed)

print(datetime.now())
'''

samp_size = 0.30
df_rows = df_modeling.shape[0]
train_rows = int(df_rows*(1-samp_size))
test_rows = df_rows - train_rows

df_modeling['ids'] = np.arange(0,df_rows)

#print(df_rows, train_rows, test_rows)

#df.modeling_train =  random.uniform(0, 1)

df_train = df_modeling.sample(train_rows, random_state = seed)
df_train.loc[:,'ttflag'] = 'Train'
df_train_ids = df_train.ids.values.tolist()
#print(len(df_train_ids))

df_test = df_modeling[~df_modeling.ids.isin(df_train_ids)]
df_test.loc[:,'ttflag'] = 'Test'
#print(df_test.shape[0])

x_train = df_train[features].values
x_test = df_test[features].values

y_train = df_train[label].values
y_test = df_test[label].values

print()
print(datetime.now())
print()

print(f"x train : {x_train.shape}, x_test : {x_test.shape}, y_train : {y_train.shape}, y_test : {y_test.shape}")

print()



2022-10-18 05:28:53.169739

x train : (170367, 4), x_test : (73015, 4), y_train : (170367,), y_test : (73015,)



/tmp/ipykernel_5090/2751971928.py:30: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test.loc[:,'ttflag'] = 'Test'


In [10]:

print(df_train.ttflag.value_counts())
print(df_test.ttflag.value_counts())


Train    170367
Name: ttflag, dtype: int64
Test    73015
Name: ttflag, dtype: int64


In [11]:


print ('Training Set: %d, Test Set: %d \n' % (len(x_train), len(x_test)))
print("Sample of features and labels:")

# Take a look at the first 25 training features and corresponding labels
for n in range(0,24):
   print(x_train[n], y_train[n])



Training Set: 170367, Test Set: 73015 

Sample of features and labels:
[  461.         17204.87907145     0.            29.        ] 26.3
[4.60000000e+02 1.75269266e+04 0.00000000e+00 2.00000000e+00] 26.23
[2.75000000e+02 1.65168931e+04 0.00000000e+00 1.00000000e+01] 16.94
[  300.         17712.70307586     0.             0.        ] 17.22
[4.5000000e+02 1.6965801e+04 0.0000000e+00 7.0000000e+00] 25.95
[3.80000000e+02 1.69415961e+04 0.00000000e+00 1.00000000e+00] 23.59
[4.50000000e+02 1.68136532e+04 0.00000000e+00 2.00000000e+00] 26.28
[6.00000000e+02 1.71662138e+04 0.00000000e+00 1.20000000e+01] 35.11
[2.88000000e+02 1.63940362e+04 0.00000000e+00 2.00000000e+00] 17.71
[3.90000000e+02 1.74381754e+04 0.00000000e+00 1.20000000e+01] 22.65
[4.610000e+02 1.719299e+04 0.000000e+00 6.000000e+00] 26.97
[3.4000000e+02 1.6596851e+04 0.0000000e+00 5.0000000e+00] 20.84
[3.05000000e+02 1.72541042e+04 0.00000000e+00 5.00000000e+00] 17.51
[3.50000000e+02 1.69981179e+04 0.00000000e+00 8.00000000e+00] 

In [12]:
#!pip install --upgrade tensorflow

In [13]:
#!pip3 install keras --upgrade

In [ ]:

print(datetime.now())

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

print(datetime.now())

from tensorflow.keras import models
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import utils
from tensorflow.keras import optimizers

# Set random seed for reproducability
tf.random.set_seed(seed)

print("Libraries imported.")
print('Keras version:',keras.__version__)
print('TensorFlow version:',tf.__version__)

print(datetime.now())


2022-10-18 05:28:53.282809


In [ ]:

# Creating Feature Normalisation
"""
#normalizer = tf.keras.layers.Normalization(axis=-1)
normalizer = tf.keras.layers.experimental.preprocessing.Normalization(axis=-1)

#normalizer.adapt(np.array(train_features))
normalizer.adapt(np.array(x_train))

print(normalizer.mean.numpy())
print()

first = np.array(train_features[:1])

with np.printoptions(precision=2, suppress=True):
  print('First example:', first)
  print()
  print('Normalized:', normalizer(first).numpy())
"""


In [ ]:

#del model

#model = Sequential()
#model.add(Dense(units=1))
#model.add(Dense(hl, input_dim=hl, activation='relu'))

#model = tf.keras.Sequential([ layers.Dense(units=1) ])



In [ ]:

from tensorflow.keras.optimizers import Adam
from tensorflow.keras import backend as K

def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_pred - y_true)))

model = Sequential([
    Dense(256, activation='relu'),
    Dense(256, activation='relu'),
    Dense(128, activation='relu'),
    Dense(1)
])

model.compile(
    loss=rmse,
    optimizer=Adam(),
    metrics=[rmse]
)

model.fit(x_train, y_train, epochs=10)

print()
print(datetime.now()


In [ ]:

model.summary()


In [ ]:

predictions_train = model.predict(x_train)
predictions_train = np.ravel(predictions_train)

predictions_test = model.predict(x_test)
predictions_test = np.ravel(predictions_test)


In [ ]:

print(rmse(y_train, predictions_train).numpy())

print(rmse(y_test, predictions_test).numpy())


In [ ]:
# Getting the output dataset together

df_train['preds'] = predictions_train
df_test['preds'] = predictions_test

df_master = df_train.append(df_test)
print()

print(df_master.shape)
print()

print(df_master.columns.values.tolist())
print()


In [ ]:

#keep_cols_for_export = ['@id_DOG', 'DogName', '@id_RACE','RaceName','Track','RaceGrade','Distance','TrainerName','RunTime','Place','x_races_tot']

# 'TrainerName', 'Track' have been dummified
cols_for_drop = ['ids']

todaydt = datetime.now().date()
pred_exp_fname = f'predictions_dataset_{todaydt}.csv'

exp_pred_ds = df_master.drop(columns = cols_for_drop)


In [ ]:

print(exp_pred_ds.columns.values.tolist())


In [ ]:

exp_pred_ds.describe()


In [ ]:

exp_pred_ds.to_csv(f'{fileloc}/{pred_exp_fname}', index = False)


In [ ]:

print("THE END")
